uploads = []
generated = []

[[outputs]]
id = "PAKGUhXmfUPE5FYky3HCo"
uri = "file://myjantes-deploy.tar.gz"
type = "unspecified"
title = "myjantes-deploy.tar.gz — Site complet prêt pour Hostinger"

[[outputs]]
id = "gJ3ZzucXu3BW70KcKLuQK"
uri = "file://myjantes-deploy.zip"
type = "unspecified"
title = "myjantes-deploy.zip — Site complet prêt à déployer sur Hostinger"

[[outputs]]
id = "1rbU5tUc8OnpsCh-lUp-6"
uri = "file://myjantes-hostinger.zip"
type = "unspecified"
title = "myjantes-hostinger.zip — prêt à déployer (30 Mo)"
